version: "3.0"
networks:
  fess_t1:
    driver: "bridge"
services:
  proxy:
    command: '"printf -- \"%s\n\" \"$${HAPROXY_CERTIFICATE}\" > /usr/local/etc/haproxy/localhost.crt; printf -- \"%s\n\" \"$${HAPROXY_CONFIG}\" > /usr/local/etc/haproxy/haproxy.cfg && haproxy -c -f /usr/local/etc/haproxy/haproxy.cfg && /docker-entrypoint.sh haproxy -f /usr/local/etc/haproxy/haproxy.cfg"'
    entrypoint: "/bin/sh -c"
    environment:
      HAPROXY_CONFIG: |-
        global
        	group root
        	log stderr format raw daemon err
        	log stdout format raw daemon info warning
        	maxconn 4096
        	maxsslrate 128
        	nbproc 1
        	nbthread 4
        	spread-checks 4
        	ssl-default-bind-ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS
        	ssl-default-server-ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS
        	tune.bufsize 16384
        	tune.maxaccept 192
        	tune.maxrewrite 1024
        	tune.ssl.default-dh-param 2048
        	tune.ssl.cachesize 320000
        	tune.ssl.lifetime 300
        	tune.ssl.maxrecord 1419
        	tune.zlib.memlevel 9
        	user root

        defaults
        	default-server inter 10s
        	default-server maxconn 128
        	log global
        	mode http
        	option abortonclose
        	option dontlognull
        	option dontlog-normal
        	option forwardfor except 127.0.0.0/8
        	option http-server-close
        	option httplog
        	option redispatch
        	retries 3
        	timeout check 15s
        	timeout client 30s
        	timeout connect 5s
        	timeout http-keep-alive 2s
        	timeout http-request 4s
        	timeout queue 120s
        	timeout server 30s

        frontend http
        	acl acl_secure_path path_beg /admin /login /logout /profile
        	backlog 1024
        	bind 0.0.0.0:80 nice 15
        	default_backend http
        	maxconn 1024
        	rate-limit sessions 1024
        	redirect scheme https code 301 if acl_secure_path !{ ssl_fc }

        frontend https
        	backlog 1024
        	bind 0.0.0.0:443 nice 30 ssl no-sslv3 no-tls-tickets crt /usr/local/etc/haproxy/localhost.crt
        	default_backend http
        	maxconn 1024
        	rate-limit sessions 144

        backend http
        	fullconn 1000
        	option httpchk HEAD / HTTP/1.1\r\nHost:\ localhost.localdomain\r\nConnection:\ close\r\nUser-Agent:\ HAProxy\r\nAccept-Encoding:\ gzip,\ deflate
        	#http-request replace-uri ^([^\ :]*\ )/\ (.*) \1/admin/\ \2
        	#http-request replace-uri ^([^\ :]*\ )/search((?:\?|\/).*)?(.*)? \1/gsa\2\3
        	http-request replace-uri ^([^\ :]*\ /gsa(?:\/|\?).*)(start=-[0-9]*)(.*)? \1start=0\3
        	http-request replace-uri ^([^\ :]*\ /gsa(?:\/|\?).*)(date:A:[SRL]:d1)(.*)? \1last_modified.asc\3
        	http-request replace-uri ^([^\ :]*\ /gsa(?:\/|\?).*)(date%3AA%3A[SRL]%3Ad1)(.*)? \1last_modified.asc\3
        	http-request replace-uri ^([^\ :]*\ /gsa(?:\/|\?).*)(date:D:[SRL]:d1)(.*)? \1last_modified.desc\3
        	http-request replace-uri ^([^\ :]*\ /gsa(?:\/|\?).*)(date%3AD%3A[SRL]%3Ad1)(.*)? \1last_modified.desc\3
        	http-request replace-uri ^([^\ :]*\ /gsa(?:\/\?|\?).*(?!(?:\?|&)site=))(site=)([^&%|]*)((?:\||%7C)[^&\n]*)?(&.*)? \1fields.label=\3\5
        	server fess_1 fess_1:8080 port 8080 check
      HAPROXY_CERTIFICATE: |-
        -----BEGIN PRIVATE KEY-----
        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDHyxkQtWKbdOrd
        sq+GNElxXLNKicuDcmZtqLOVDU3a11iRwBeT5KjW0retPBCm3qCYf7p9Zeoo/z0l
        uviZGS71Ka/dLIz9vkSAYIzM+PKFxQjpfQWqpFoHA67dTtwN1C33dAQesDocx+BJ
        pMmhohGLkLANQHd9g8Yt8OKq/lghlwfcl44A08xkjp2az5ICNJyFNf9gwZFwA8/9
        9pRwu052DqftX3xgq68ubaPlI+/tbWu+zvGW0YeZEk6Pj/nvSwUIBpNCRqOq0QJr
        99qsNaCo3/nUThXyqTS7y9Z3mElSxVcdtTUmovOIumeay40RU89BFkV71CGxfCNX
        LXWXpe13AgMBAAECggEANykdvH03wk/fYGIrD9RzynabkaLFq370RKZlHmvT6O23
        qFXurIhfDSCUUaHZvxiMIk5xgJmYssT1butWI37OdiWSRnA8ZPoZE5CUjyrUWpZx
        xXUdEWXa7UDZEITrQG4qWr2PPaHOCZAtnmd+u79xNKU31hDMbLzrBFgTXL5oOq1o
        4PW7FN5/0gCi5iAriy5dhFtjycitFVYRriIojfi3gHAZxA/icLyYJyXbH6Fb/pEc
        l8nBRpZbyYBvN5iTH0+uzXNNtMlT+Jka83zXgQeEAdnwGns1vqx2jYqfwFYe0Dhk
        JFYLG7YT0d6k2yEq6NTiobGyEJa60O+vk92BPmMpQQKBgQD0KZnOO7fp9EUe6K4m
        0b77pcguRww3+1eEPy46pvpUydpj8l3e36eo/mkNUrVXz0yG0SZc/3Em4u9BDxdr
        wuNqeL55Z+7HF0CmuqvJWbTVNxPN6KOmvYerSD1SLgvaJTd5zYr35In/tJKH/0XH
        P5cMnOKeO1E2vS88PdLmefMnBwKBgQDRetBN1sze1nz7arHSQUTdBXJmGBbDOoHO
        5b/aHJamokcUd9Pv86GCyA5KQ11A78qLcQj43rBzupOM1iC9mazQ2FBY5Yi4IaBS
        6YaK+LQNuWrNqI5GqPmCEN6bOOl1HYyrwWCa5TYFD+lpldWnWAIJxWOenhPG4Xnb
        3yHWOiF6EQKBgCW6k/DBW58ERvYKwHZxLNDYAkHcaq/v38sotC0OBlq5wkx1dDnv
        V4oOng8X+7uw5cNjaEkwk7yNjqj/+v+E4v1d4RkDjWsoVa4t5EO93+qekynbTAaE
        /QTjqc4cHWq9G4Bv2YyKvSRNM+Nd99tdISsqxv3qbpdFzpnBd+hzabZbAoGBAJVc
        1XP66Z8mHn2B6QK66SgS/yvOl0RizjXA2ZfidISiBr6QZjycYZgHnzDScYags7HT
        SgtxdS0/Zn+wGi42ieNrqXaJS3/G8jLMMdObW37Bq2ayfafiSe20q5TP8p5AEJJS
        0tf/ARKA8vQHEw08Ek/3P33UxtMy6BmfMtg2ILKRAoGBAOMdOgcya0HNpe23hsvQ
        POypVaRIZuZ92tfbtyRhOO3hYbJPakncVL3BFBwLqSBCxTjW3hFBqwaLHDTA0o/u
        GWl0e6Xf7GEg0gonkPI+UkLQ8NNT51FVWd/HQ5Pv72RoEeAH/0QETYhRncTHMnvA
        5wUawXdc5bsIeXqhWNqqp+M1
        -----END PRIVATE KEY-----
        -----BEGIN CERTIFICATE-----
        MIIC8jCCAdqgAwIBAgIJALoFrjE0+dLNMA0GCSqGSIb3DQEBCwUAMCAxHjAcBgNV
        BAMTFWxvY2FsaG9zdC5sb2NhbGRvbWFpbjAeFw0xOTA5MDkwNzQzNDNaFw0yMDA5
        MDgwNzQzNDNaMCAxHjAcBgNVBAMTFWxvY2FsaG9zdC5sb2NhbGRvbWFpbjCCASIw
        DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMfLGRC1Ypt06t2yr4Y0SXFcs0qJ
        y4NyZm2os5UNTdrXWJHAF5PkqNbSt608EKbeoJh/un1l6ij/PSW6+JkZLvUpr90s
        jP2+RIBgjMz48oXFCOl9BaqkWgcDrt1O3A3ULfd0BB6wOhzH4EmkyaGiEYuQsA1A
        d32Dxi3w4qr+WCGXB9yXjgDTzGSOnZrPkgI0nIU1/2DBkXADz/32lHC7TnYOp+1f
        fGCrry5to+Uj7+1ta77O8ZbRh5kSTo+P+e9LBQgGk0JGo6rRAmv32qw1oKjf+dRO
        FfKpNLvL1neYSVLFVx21NSai84i6Z5rLjRFTz0EWRXvUIbF8I1ctdZel7XcCAwEA
        AaMvMC0wKwYDVR0RBCQwIoIVbG9jYWxob3N0LmxvY2FsZG9tYWlugglsb2NhbGhv
        c3QwDQYJKoZIhvcNAQELBQADggEBAJ5X4X5SS4LM3slVoDUVSCD/H+DCRx3oPbZK
        k/+XGoj6lKT/g49lkZ+TXJYFoWbEbNARKAlQHODWRclzThGtmqZh7jVkDk050Nva
        s/NEJiYsklVcbO604gZsjZtnK2xNddho0DewcYfLKP+eqYbAWBeh3HfGi+qvxB6r
        /T0ssxUsBpKnQk/zh6b3tZOwBr/wcfa+DzjHi6uXuM7h48XN2r/yCB5C019j7rvJ
        d0rBuLEARd64Zlew7AEJ4UsIcdK7gmj+/z4RpzvgiBSQcWfFBDLVEjmdHaucsZEY
        aM8FF3bsHIm2Le3UvCIDPgixf+NKM4sD+7yMZ+UMTxOCOENKI2o=
        -----END CERTIFICATE-----
        -----BEGIN DH PARAMETERS-----
        MIIBCAKCAQEAmwbvw84P+F1GWmJF7UFY6xPcF7z/5OnhrblMc4W5sALOc+Jwziak
        shQYFG/eBQhrKmMilAjwQPqanufUH8c1b19J3yXMKhovrf+UjMVhm1ugPc66JQy4
        Ect8PgkX/6L385kyKaH2JBTaUX5X0+aTrqRZjLMku92ZcZt6umw4ADvESGyPS96E
        vYG19DqKjebBQkqdLjt0BISpNhHQSncS2t6X3OkDUoWhk6/yuMC9LZwuUfxWdQKN
        yBwHkhAPuwDaJsaa94QOalBQt4zWgEfW2lRe/MnKWdUjutrIQpB1xiOVllbiSvbG
        5DdlkB/jHf8UHoQ5GJezddIUhUvuprA7kwIBAg==
        -----END DH PARAMETERS-----
    image: "haproxy:2.0.5-alpine"
    networks:
      - "fess_t1"
    ports:
      - "80:80"
      - "443:443"
    restart: "always"
    ulimits:
      nofile:
        soft: 524288
        hard: 1048576
      nproc: 65535
  fess:
    build: "./fess"
    networks:
      fess_t1:
        aliases:
          - "fess_1"
    restart: "always"
