version: "3.0"
networks:
  fess_t1:
    driver: "bridge"
services:
  proxy:
    command: '"printf -- \"%s\n\" \"$${HAPROXY_CERTIFICATE}\" > /usr/local/etc/haproxy/localhost.localdomain.crt; printf -- \"%s\n\" \"$${HAPROXY_CONFIG}\" > /usr/local/etc/haproxy/haproxy.cfg && haproxy -c -f /usr/local/etc/haproxy/haproxy.cfg && /docker-entrypoint.sh haproxy -f /usr/local/etc/haproxy/haproxy.cfg"'
    entrypoint: "/bin/sh -c"
    environment:
      HAPROXY_CONFIG: |-
        global
        	group root
        	log 127.0.0.1 local2
        	maxconn 4096
        	maxsslrate 128
        	nbproc 1
        	spread-checks 4
        	ssl-default-bind-ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS
        	ssl-default-server-ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS
        	tune.bufsize 16384
        	tune.maxaccept 192
        	tune.maxrewrite 1024
        	tune.ssl.default-dh-param 2048
        	tune.ssl.cachesize 320000
        	tune.ssl.lifetime 300
        	tune.ssl.maxrecord 1419
        	tune.zlib.memlevel 9
        	user root

        defaults
        	default-server inter 10s
        	default-server maxconn 128
        	log global
        	mode http
        	option abortonclose
        	option dontlognull
        	option dontlog-normal
        	option forwardfor except 127.0.0.0/8
        	option http-server-close
        	option httplog
        	option redispatch
        	retries 3
        	timeout check 15s
        	timeout client 40s
        	timeout connect 5s
        	timeout http-keep-alive 15s
        	timeout http-request 4s
        	timeout queue 120s
        	timeout server 40s

        frontend http
        	acl acl_secure_path path_beg /admin /login /logout /profile
        	backlog 1024
        	bind 0.0.0.0:80 nice 15
        	default_backend http
        	maxconn 1024
        	rate-limit sessions 1024
        	redirect scheme https code 301 if acl_secure_path !{ ssl_fc }

        frontend https
        	backlog 1024
        	bind 0.0.0.0:443 nice 30 ssl no-sslv3 no-tls-tickets crt /usr/local/etc/haproxy/localhost.localdomain.crt
        	default_backend http
        	maxconn 1024
        	rate-limit sessions 144

        backend http
        	fullconn 1024
        	option httpchk HEAD / HTTP/1.1\r\nHost:\ localhost.localdomain\r\nConnection:\ close\r\nUser-Agent:\ HAProxy\r\nAccept-Encoding:\ gzip,\ deflate
        	#reqrep ^([^\ :]*\ )/\ (.*) \1/admin/\ \2
        	#reqrep ^([^\ :]*\ )/search((?:\?|\/).*)?(.*)? \1/gsa\2\3
        	reqrep ^([^\ :]*\ /gsa(?:\/|\?).*)(start=-[0-9]*)(.*)? \1start=0\3
        	reqrep ^([^\ :]*\ /gsa(?:\/|\?).*)(date:A:[SRL]:d1)(.*)? \1last_modified.asc\3
        	reqrep ^([^\ :]*\ /gsa(?:\/|\?).*)(date%3AA%3A[SRL]%3Ad1)(.*)? \1last_modified.asc\3
        	reqrep ^([^\ :]*\ /gsa(?:\/|\?).*)(date:D:[SRL]:d1)(.*)? \1last_modified.desc\3
        	reqrep ^([^\ :]*\ /gsa(?:\/|\?).*)(date%3AD%3A[SRL]%3Ad1)(.*)? \1last_modified.desc\3
        	reqrep ^([^\ :]*\ /gsa(?:\/\?|\?).*(?!(?:\?|&)site=))(site=)([^&%|]*)((?:\||%7C)[^&\n]*)?(&.*)? \1fields.label=\3\5
        	server fess_1 fess_1:8080 port 8080 check
      HAPROXY_CERTIFICATE: |-
        -----BEGIN PRIVATE KEY-----
        MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDkW4FhgHOwlfLY
        1fV57LpBjDrDZKzxw0BeTeIfRLpgWkYZ9h9y3UmtkMKuHzhG4PLU1X/hVbcWDhHo
        VUJiuvlFgd9WyyTyOGEyPbBMva+agIDN5sQZjXXkcJ4ICPXpz2NdVwIgWRt0M0Sy
        YTElZaVZzmaxo6RDS9fz6GLeAh5S7k5/ufykocBnCndIU+agnDymfhW4O7xv3mom
        PUNMPkWerziVRxaqdyqcqBBQYHHGz3G5Il2Dq3rBeXRit5xuez4EmhDyANn5uFAp
        k/sBiGzQd9PEqyedmIlAmOYUeqWmbS+Sm8UOvif84wCU7t+EVtkAZcQ1bnBtXYRy
        kdnl/Qz9AgMBAAECggEADR5op2ZOvyVOJ0Dbcl60MJHSymjdOqJh70kAJZW4M1Lc
        Vh96nQmzcuIvHPu0KvY/XRTK3PIkq4KxaqyDPNLLAUA9yWmwPK4af11l5HK9RN3/
        CFUqjOFAlZgWrBV/syfz6GfYOm2EEz/iwXCt9x0Iy8j8w1XIWQlhZaTDEUgD3/Wv
        BI5NHZ0IycpXBH1jjMZ+7xAoEKhPSS566FxecwTYW1Kjh9A+QAwz7DEo3Eh8+8dx
        LpXB24a/4Yk5zKcnwK2OjUsyBMFUJjrQnA/hK4qzaCSgeOHlEpo5sdOj9LBhc4Om
        xScCRam2idHt4IOloiniAkVqiN1O7UusVLm4HB8ojQKBgQD8Qj5oLyQ+iydTH9jK
        8/dagGb8mD6pQGpP3KrJMIcp578jT4sGaEThPqYjd5kHEjPw5+HAhHohHgO/VVjN
        mv546+TEDFP3bR7SFZ+CtfnUkPIx1l9ZmIO//NvBlDkdMLMA9O9j3N89qTAz8Ac/
        ESJBIj8ooWpz1bM645GnhB+sSwKBgQDnvoPUYTe3p5c0SNGYOr/3DZsilr/zmjiZ
        7JrJBhKr639+be9Twe16XVJtZQc+5hQg4ALpeLnbFLtPnMYzQ/9fQCmM0McAXGTO
        ul9o5lJa3Ash3LqAz+ObF7k2s4BIWRgzDIUMxIlL3PKqwK3SPCmiZX/UeH0ICuAY
        thgkYt3O1wKBgQCqkbhVBhtB1yHeCRi0EsbcgRoiDmfAVfgMzC8HHzMl2Lfbjnt4
        96QrkgsQzFvC9kH80S5K2Mkj/4GVLIaBcB5FcWwcTCGymixO7aQP5DBr1R6PKF8M
        3B2qAbYubKU54aYILZZ5Ne4VaYNYeyLLODCrThbayFqMvKEWXq4sUSCBhQKBgQDE
        XZ5/G1GHAS8SUpGnGEEJKjJGAM7tr8Q+SUpvBAJWQtppWuXsZuq/QMxTfcPB/FsZ
        8DcHdhCmHs8JCqK3VerR3yBV/aJiH+gbc7jcvi0SaFnWe55c/8qw5E1AmKEerL/g
        ob8rrm1YJwRIw7OF7QyqWq8SbnYjlnOE/OdADbY9SQKBgQCQFXd69+cbBV+Jt03+
        mexGBKd0DITokntls8cdJLTMBYLZYqlkIZIhs2sAkugRkhNwa94Q9BxvF/InrGLI
        FcJxh5rOgPb/2wNlY3z38cnDJuQZWqmZnYfsc0JPJ/hm3b9EdB9tkXkGPFNe4utB
        BSgKg2L3X2JK2WHiic5W8idxvw==
        -----END PRIVATE KEY-----
        -----BEGIN CERTIFICATE-----
        MIIC8jCCAdqgAwIBAgIJALkijHOxizhYMA0GCSqGSIb3DQEBCwUAMCAxHjAcBgNV
        BAMTFWxvY2FsaG9zdC5sb2NhbGRvbWFpbjAeFw0xODA5MTAyMzI2NDZaFw0xOTA5
        MTAyMzI2NDZaMCAxHjAcBgNVBAMTFWxvY2FsaG9zdC5sb2NhbGRvbWFpbjCCASIw
        DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAORbgWGAc7CV8tjV9XnsukGMOsNk
        rPHDQF5N4h9EumBaRhn2H3LdSa2Qwq4fOEbg8tTVf+FVtxYOEehVQmK6+UWB31bL
        JPI4YTI9sEy9r5qAgM3mxBmNdeRwnggI9enPY11XAiBZG3QzRLJhMSVlpVnOZrGj
        pENL1/PoYt4CHlLuTn+5/KShwGcKd0hT5qCcPKZ+Fbg7vG/eaiY9Q0w+RZ6vOJVH
        Fqp3KpyoEFBgccbPcbkiXYOresF5dGK3nG57PgSaEPIA2fm4UCmT+wGIbNB308Sr
        J52YiUCY5hR6paZtL5KbxQ6+J/zjAJTu34RW2QBlxDVucG1dhHKR2eX9DP0CAwEA
        AaMvMC0wKwYDVR0RBCQwIoIVbG9jYWxob3N0LmxvY2FsZG9tYWlugglsb2NhbGhv
        c3QwDQYJKoZIhvcNAQELBQADggEBAJtCSp8S+QspigrQ6qvqBzyBU2Cmglj54oeM
        Q511NiVfbkvq9xh95koccw4DPFja/btXUdCn/RAO2zAhs7Iss9RmBJDeRKp9CWoe
        MaNvJyx4ko5MIPfgcQc0WGV0OszYRzxQGpjErsKNfSB5dnQ7f2/gazvS6NB92Dkb
        3Sk4fHdPw+pNHbNef4MR57/NfgxLxXhkASdyXf+Qk/abKKCrKIockUT+btVzPFwj
        3oSOk6d444GogdASIguH3bGCpuvUyRHdPT/UBGNzHuPI50cN3d6v1rrXyTUfcr7Z
        gt6oCL36AXStNKzQtCDqwB/njbqp3saJTKrj0lS9CK/ohSpv65Q=
        -----END CERTIFICATE-----
        -----BEGIN DH PARAMETERS-----
        MIIBCAKCAQEAjn+R9oe/uM1H2gJjSutzDEnbmNCZ0ekDU8YNR2L2eBa2BcfsbV5V
        3FaJE6SB/BIF2Esp5zKrOylmOHI/9KDo0E1Kd8YaXDj69Pq0Fv2Yllti5fJpwDiY
        MP+dVN0sCCrxniBVP1qf26dDE16z0w56PzH/gDYZdGrLZQ0Qsc65g3wDkMEa0MPl
        gjUr/l01e5AT6TGA5HHxDD0jP/QARnusVq5doFT9yrmbvP3Kx1gQCbek+ButGjAW
        VVYD3t5OLYSei8tz9N4RW+vBBgsdGBzd6+1oeZNRg5sCjUonBAqeBqvclPVNavf5
        3f3lv7hmvLNAgxqLuIfqbFFVQ8BOiQGJWwIBAg==
        -----END DH PARAMETERS-----
    image: "haproxy:1.8.13-alpine"
    networks:
      - "fess_t1"
    ports:
      - "80:80"
      - "443:443"
    restart: "always"
    ulimits:
      nofile:
        soft: 524288
        hard: 1048576
      nproc: 65535
  fess:
    build: "./fess"
    networks:
      fess_t1:
        aliases:
          - "fess_1"
    restart: "always"
